import { GoogleGenAI } from "@google/genai";
import { createServiceClient } from "@/lib/supabase";
import type { ImageStyle } from "@/types/content";
import { randomUUID } from "crypto";

// ---------------------------------------------------------------------------
// Locked prompt constants
// ---------------------------------------------------------------------------

const PROMPT_AESTHETIC_FLATLAY =
  "cozy home desk flat lay shot from above, open journal with pen, ceramic coffee mug with latte art, small lit candle flickering gently, dried flowers in mini white vase, gold paper clips scattered, neutral linen surface, gentle ambient motion, soft diffused morning light, no people, no text, muted and slightly desaturated, film photography aesthetic, cream and warm taupe palette, quiet luxury minimal styling, cinematic lifestyle photography, ultra realistic, 4k";

const PROMPT_WOMAN_LIFESTYLE =
  "cozy bedroom reading nook, faceless woman sitting on white linen bed from behind wearing cream knit sweater, open book in lap, lit candle on wooden nightstand, soft muted morning light through sheer white curtains, woman positioned in bottom half of frame, top 40% of image is empty window and curtains with no subject, muted and slightly desaturated, film photography aesthetic, cooler warm tones not orange, cream and taupe palette, no text, cinematic lifestyle photography, ultra realistic, 4k";

const PROMPT_AESTHETIC_ONLY =
  "minimalist cream background with subtle linen texture, soft warm light casting gentle shadow diagonally from left side, small lit cream pillar candle in ceramic holder bottom center, single dried flower stem laying diagonally across frame, no people, no text, no words, muted and slightly desaturated, film photography aesthetic, cream and warm taupe palette, quiet luxury, lots of empty negative space in center and upper half for text overlay, soft bokeh background, cinematic lifestyle photography, ultra realistic, 4k";

export function getPromptForStyle(imageStyle: ImageStyle): string {
  switch (imageStyle) {
    case "aesthetic_flatlay":
      return PROMPT_AESTHETIC_FLATLAY;
    case "woman_lifestyle":
      return PROMPT_WOMAN_LIFESTYLE;
    case "aesthetic_only":
      return PROMPT_AESTHETIC_ONLY;
  }
}

// ---------------------------------------------------------------------------
// Retry helper
// ---------------------------------------------------------------------------

async function callWithRetry<T>(fn: () => Promise<T>): Promise<T> {
  try {
    return await fn();
  } catch (error) {
    console.error("Imagen 3 call failed, retrying in 10s…", error);
    await new Promise((r) => setTimeout(r, 10_000));
    return await fn();
  }
}

// ---------------------------------------------------------------------------
// Upload to Supabase Storage and return public URL
// ---------------------------------------------------------------------------

async function uploadToSupabase(imageBytes: Buffer, filename: string): Promise<string> {
  const supabase = createServiceClient();
  const bucket = "generated-images";

  // Ensure bucket exists (idempotent)
  await supabase.storage.createBucket(bucket, { public: true }).catch(() => {
    // Bucket may already exist
  });

  const { error } = await supabase.storage
    .from(bucket)
    .upload(filename, imageBytes, {
      contentType: "image/png",
      upsert: true,
    });

  if (error) {
    throw new Error(`Supabase upload failed: ${error.message}`);
  }

  const { data: urlData } = supabase.storage.from(bucket).getPublicUrl(filename);
  return urlData.publicUrl;
}

// ---------------------------------------------------------------------------
// Imagen 3 generation via @google/genai SDK
// ---------------------------------------------------------------------------

export async function generateBackground(imageStyle: ImageStyle): Promise<string> {
  const prompt = getPromptForStyle(imageStyle);
  console.log(`Generating Imagen 3 background (style: ${imageStyle})…`);

  const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY! });

  const result = await callWithRetry(async () => {
    const response = await ai.models.generateImages({
      model: "imagen-4.0-generate-001",
      prompt,
      config: {
        numberOfImages: 1,
        aspectRatio: "3:4", // portrait for carousels/single images (896x1280)
      },
    });
    return response;
  });

  if (!result.generatedImages || result.generatedImages.length === 0) {
    throw new Error("No image generated by Imagen 3");
  }

  const image = result.generatedImages[0];
  const imageBytes = image.image?.imageBytes;
  if (!imageBytes) {
    throw new Error("Imagen 3 returned empty image data");
  }

  // Convert to Buffer and upload to Supabase Storage
  const buffer = Buffer.from(imageBytes as string, "base64");
  const filename = `${imageStyle}/${randomUUID()}.png`;
  const publicUrl = await uploadToSupabase(buffer, filename);

  console.log("Imagen 3 background generated and uploaded:", publicUrl);
  return publicUrl;
}
